Jtest17
FRC125/NU17 pull request #1
Opened 2017-01-14 19:44 UTC by KevinHenriquez

Merging Climber. I've created a subsystem and command class that will be used on the climber system. There is one motor along with a micro-switch that will be used to find out whether or not we need to stop the motor or not.

2017-01-14 19:53 UTC, teresakrause commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Did you mean to include this file? It's also in the .gitignore

2017-01-14 20:05 UTC, MiloDavis commented on src/lib/Utils.java
> +	public static double deadband(double value, double deadband, double center){
This needs a comment explaining what this does and what it is for.  You should also have tests.

2017-01-14 20:07 UTC, Jw0x47 requested changes
Mostly style stuff definitely worth standardizing on some style guide before merging.

2017-01-14 20:07 UTC, Jw0x47 commented on src/com/nutrons/nu17/OI.java
> +	 * Make robot shoot
@MiloDavis Not sure on what you want the style to be here, couldn't these be regular comments? 
The 3 lines here are just making things harder to read IMO

2017-01-14 20:07 UTC, Jw0x47 commented on src/com/nutrons/nu17/OI.java
> +
nit extra newline.

2017-01-14 20:07 UTC, Jw0x47 commented on src/com/nutrons/nu17/OI.java
> +	 * @return
Empty return comment?

2017-01-14 20:07 UTC, Jw0x47 commented on src/com/nutrons/nu17/Robot.java
> +	public static TwinShooter twinShooter = new TwinShooter(RobotMap.TWIN_A, RobotMap.TWIN_B, RobotMap.ENCODER_A,
Easier to read if you write it like:
```
public static TwinShooter twinShooter = new TwinShooter(
  RobotMap.TWIN_A,
  RobotMap.TWIN_B,
  RobotMap.ENCODER_A,
  RobotMap.ENCODER_B,
  RobotMap.ENCODER_A,
  RobotMap.ENCODER_B);
```

2017-01-14 20:07 UTC, Jw0x47 commented on src/com/nutrons/nu17/Robot.java
> +
Why are these functions overridden and empty?

2017-01-14 20:07 UTC, Jw0x47 commented on src/com/nutrons/nu17/Robot.java
> +	}
Inconsistent newlines here. Some methods are empty and have a newline some do not.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/commands/ChangePlacerPositionCmd.java
> +public class ChangePlacerPositionCmd extends Command {
There are tabs here. Pls no.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/commands/GroundIntake.java
> + * @author Josh Young
Don't bother with `@author`. Git will handle that for you.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/subsystems/Climber.java
> +		// setDefaultCommand(new MySpecialCommand());
Don't leave code commented out unless you've got a reason, in a comment next to it. 
Otherwise its just confusing  & hard to read.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/subsystems/Climber.java
> +
Why is there a newline here?

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +	public PIDController driveDistance = new PIDController(this.P_DISTANCE, this.I_DISTANCE, this.D_DISTANCE,
Again easier to have each argument on a new line.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +
Extra newline.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +			// TODO Auto-generated method stub
Why is this empty.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/subsystems/DrivetrainGyro.java
> +	public PIDController driveDistanceControl = new PIDController(RobotMap.P_DRIVE, RobotMap.I_DRIVE, RobotMap.D_DRIVE,
Arguments on different lines again.

2017-01-14 20:07 UTC, jonathanwgoodwin commented on src/com/nutrons/nu17/subsystems/GearPlacer.java
> +	 * encoder unknown private class EncoderWrapper implements PIDSource {
Why is this commented out?

2017-01-14 20:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/TwinShooter.java
> +	private class EncoderWrapperB implements PIDSource {
Why B? Could you write this in a class that abstracts over the differences?

2017-01-14 20:08 UTC, teresakrause commented on src/com/nutrons/nu17/RobotMap.java
> +	// PID constants of drive train
Are these ports? If not, is there a better place for these?

2017-01-14 20:09 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/TwinShooter.java
> +	/**
These should all just be abstracted over the Encoder value

2017-01-14 20:22 UTC, MiloDavis commented on src/com/nutrons/nu17/commands/GroundIntake.java
> + * @author Josh Young
Also turn this off in your IDE.

2017-01-15 15:43 UTC, sytect commented on src/com/nutrons/nu17/subsystems/GearPlacer.java
> +	 * encoder unknown private class EncoderWrapper implements PIDSource {
i got rid of it but i commented it out saying "encoder unknown" because we dont know if we'll have an encoder on the test bot yet

2017-01-15 15:44 UTC, sytect commented on src/com/nutrons/nu17/subsystems/TwinShooter.java
> +	/**
can you explain to me what you mean? im not sure

2017-01-15 15:45 UTC, sytect commented on src/lib/Utils.java
> +	public static double deadband(double value, double deadband, double center){
what are we testing and how?

2017-01-15 16:39 UTC, kreeve commented
Plz don't check in the Javadoc files.

2017-01-15 17:41 UTC, MiloDavis commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Still an issue

2017-01-15 17:41 UTC, MiloDavis commented on README.md
> +To Generate a Javadoc:
These are instructions for Eclipse.  Make that clear

2017-01-15 17:41 UTC, MiloDavis commented on README.md
> +2) Javadoc Command: C:\Program Files\Java\jdk1.8.0_111\bin\javadoc.exe
This will be different for other people because it bakes in a version of the jdk

2017-01-15 17:41 UTC, MiloDavis commented on README.md
> +5) click next and give it a title if you'd like
Ignore the title.  Not important

2017-01-15 17:41 UTC, MiloDavis commented on build.properties
> +simulation.world.file=/usr/share/frcsim/worlds/GearsBotDemo.world
Add newline to end of file

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/OI.java
> +public class OI {
JavaDoc

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/OI.java
> +	private Button shootShooterCmd = new JoystickButton(this.operatorPad, 0);
No magic numbers.  These are constants that should live in robotMap

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/OI.java
> +	public Joystick driverPad = new Joystick(1);
Magic numbers

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/OI.java
> +	public Joystick operatorPad = new Joystick(2);
Magic numbers

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/OI.java
> +
Extra line breaks

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/OI.java
> +	 * Return the y axis of driver's right joystick.
Cut description if its fully specified in the @return

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/Robot.java
> +	public static TwinShooter twinShooter = new TwinShooter(
Add `final` keyword to all of these and use proper constant variable naming

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
> +}
Add newline to end of file

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/commands/ChangePlacerPositionCmd.java
> +		return false;
Does this ever finish?

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/commands/ClimberCmd.java
> +		return false;
Does this ever finish?

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/commands/GroundIntakeCmd.java
> +		return false;
When does this finish?

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/commands/GroundIntakeSpitCmd.java
> +		return false;
Does this finish?

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +	private Talon driveLeftA = new Talon(RobotMap.DRIVE_LEFT_A);
Add final to all of these.  Initialize in constructor if not static

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +
Too many newlines

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +			drive(output, -output, output, -output);
This needs an implementation comment.  What do the arguments mean?

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/DrivetrainGyro.java
> +	private Talon frontRight = new Talon(RobotMap.FRONT_RIGHT);
Add final to all of these

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/GearPlacer.java
> +	public Talon gearPlacer = new Talon(RobotMap.PLACER);
Make this final and initialize in constructor

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/GearPlacer.java
> +//import edu.wpi.first.wpilibj.PIDSource;
Remove unused imports

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/GearPlacer.java
> +}
Add newline at end of file

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/GroundIntake.java
> +	private Talon rollerA = new Talon(RobotMap.ROLLER_A);
Make final and initialize in constructor

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/HoodShooterFlywheel.java
> +	private Talon flyWheelLeft = new Talon(RobotMap.FLY_WHEEL_L);
Initialize in constructor or make static

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/HoodShooterFlywheel.java
> +	private final double P_TURN = 0.001;
Make these static

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/HoodShooterFlywheel.java
> +
Extra newlines

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Shooter.java
> +	public PIDController ShootSpeedControl = new PIDController(this.P_SHOOT, this.I_SHOOT, this.D_SHOOT,
Break this into multiple lines

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Shooter.java
> +	public static double holdShoot;
Is this a constant?

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/TwinShooter.java
> +	public TwinShooter(
These aren't constants.  Rename

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/TwinShooter.java
> +	public double P_SHOOT = 0.025;
These should be final

2017-01-15 17:41 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/TwinShooter.java
> +	private class HoldShooterOutputA implements PIDOutput {
These should be one class that takes a parameter

2017-01-16 04:20 UTC, sytect commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +			drive(output, -output, output, -output);
How do i write a javadoc if the method has @Override on it?

2017-01-16 04:22 UTC, KevinHenriquez commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +			drive(output, -output, output, -output);
do we need it ? if not take it out fam

2017-01-16 04:37 UTC, sytect commented on build.properties
> +simulation.world.file=/usr/share/frcsim/worlds/GearsBotDemo.world
added but didnt get rid of this message

2017-01-16 04:37 UTC, sytect commented on src/com/nutrons/nu17/subsystems/GearPlacer.java
> +//import edu.wpi.first.wpilibj.PIDSource;
ending up using this import for a port constant

2017-01-16 19:22 UTC, teresakrause commented on src/lib/Utils.java
> +	 * Gets rid of miniscul unwanted input and only returns user input.
minuscule?

2017-01-16 19:50 UTC, MiloDavis commented on build.properties
> +simulation.world.file=/usr/share/frcsim/worlds/GearsBotDemo.world
It might not show up on the diff

2017-01-16 20:07 UTC, MiloDavis submitted a review, later dismissed
Still some issues, but we'll need to do another round of review once we get the robot, so I'm punting that one down the road so we can make progress

2017-01-16 20:07 UTC, MiloDavis commented on src/com/nutrons/nu17/OI.java
> +		return Utils.deadband(this.DRIVER_PAD.getRawAxis(1), 0.005, 0.0);
Why does this value differ rom the getRightJoystickX value?

2017-01-16 20:36 UTC, MiloDavis commented on .gitignore
> +*.class
Use Unix newline characters

2017-01-16 20:41 UTC, MiloDavis approved these changes
Needs testing, but most style issues are fixed.

2017-01-16 20:41 UTC, merged