Fix style errors
FRC125/NU17 pull request #11
Opened 2017-01-20 16:00 UTC by sytect

2017-01-20 16:02 UTC, kreeve requested changes
ModifierOrder errors can be fixed by changing `static public` to `public static`. See http://checkstyle.sourceforge.net/config_modifier.html#ModifierOrder

2017-01-21 16:09 UTC, sytect commented
I changed final static to static final since thats the order. What should I do about the OI error?

2017-01-21 16:09 UTC, sytect commented
WOOPS

2017-01-21 16:18 UTC, kreeve approved these changes

2017-01-21 16:18 UTC, merged