Dt workingfrommaster
FRC125/NU17 pull request #3
Opened 2017-01-17 15:51 UTC by JYoung413

Alright so I rewrote the drivetrain and this time used alot more stuff from WPILIB then used previously making it much more efficient. I also made a new GyroWrapper class for PID controllers that require such and updated everything else to fit the needs of the new classes. Also I deleted unused variable from a shooter class when I noticed it.

2017-01-17 16:07 UTC, MiloDavis reviewed
Decent, but watch your style and logic.

2017-01-17 16:07 UTC, MiloDavis commented on src/lib/GyroWrapper.java
> +	public GyroWrapper() {
Unless this constructor is specifically required by the library, delete it.

2017-01-17 16:07 UTC, MiloDavis commented on src/lib/GyroWrapper.java
> +	public GyroWrapper(PIDSourceType pidSource,AnalogGyro gyro,int gyroSource) {
You need spaces after commas

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
> +	public static final int LEFT_DRIVE_MOTOR_A = 0;
Giving the direction "front, center, back" is clearer when translating this into wiring.

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> + * Drivetrain code four a 4 wheel drive
We know this is code, so you don't need to say it.

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
>  package com.nutrons.nu17.subsystems;
Check the formatting on this entire class.  Comments should end on the line before the class starts.  Indentation should be consistent.  Fix this stuff in this PR

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +		// Encoder Ports Not FINAL Needs Tuning!
This comment should read:
`// TODO: Tune PID constants`

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +	// Sensors
Fix the indentation here.  The declarations should be indented to the same level as the comment.

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +			this.ENC_A.reset();
Extra newlines

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +
Extra newline

2017-01-17 16:07 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/TwinShooter.java
> +
Too many newlines

2017-01-17 16:07 UTC, MiloDavis commented on src/lib/GyroWrapper.java
> +	@Override
The javadoc goes before the `@Override` annotation.

2017-01-17 16:07 UTC, MiloDavis commented on src/lib/GyroWrapper.java
> +	}
Need a line break between methods

2017-01-17 16:45 UTC, JYoung413 commented
Fixed issues, please review

2017-01-18 00:16 UTC, MiloDavis reviewed
The biggest issue is variable naming.  Fix and I'll merge

2017-01-18 00:16 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +	private final Encoder ENC_A = new Encoder(RobotMap.DT_ENCODER_1, RobotMap.DT_ENCODER_2);
Make naming consistent with wheels and motors

2017-01-18 00:16 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +	public Talon leftDriveA = new Talon(RobotMap.FRONT_LEFT);
Same naming convention here too

2017-01-18 00:16 UTC, MiloDavis commented on src/com/nutrons/nu17/subsystems/Drivetrain.java
> +	private HoldPID driveHoldA = new HoldPID();
These need real names.  A B and C are not descriptive enough

2017-01-18 01:10 UTC, MiloDavis requested changes

2017-01-18 01:10 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
>  	// Ports of encoders
If this is attached to a wheel, tell me which wheel

2017-01-18 22:05 UTC, MiloDavis requested changes

2017-01-18 22:05 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
> +	public static final int ROLLER_FIRST = 0;
This is just as bad.  I should be able to read the variable and point to the bit of the robot it attaches to.

2017-01-18 22:05 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
> +	public static final int DRIVE_DISTANCE_ENCODER_1 = 1;
1 and 2 are not helpful Josh.  Once again, I should be able to look at the variable and find it on the Robot.  1 and 2 have no meaning on the robot.

2017-01-18 22:05 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
> +	public static final int TWIN_LEFT_ENCODER_1 = 9;
What do 1 and 2 mean.  Front and back?  Left and right?  Make this explicit.

2017-01-19 03:19 UTC, MiloDavis requested changes

2017-01-19 03:19 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
> +	// Paramter naming convention : Subsystem SIDE_PLACEMENT
Put this at the top of the file

2017-01-19 03:19 UTC, MiloDavis commented on src/com/nutrons/nu17/RobotMap.java
> +	public static final int ROLLER_FRONT = 0;
Missing subsystem

2017-01-19 03:19 UTC, MiloDavis commented on .classpath
> +	<classpathentry kind="var" path="USERLIBS_DIR/CTRLib.jar"/>
Is this library going to be on everyone's system

2017-01-20 00:39 UTC, MiloDavis commented on .classpath
> +	<classpathentry kind="var" path="USERLIBS_DIR/CTRLib.jar"/>
@JYoung413

2017-01-20 00:43 UTC, MiloDavis approved these changes

2017-01-20 00:43 UTC, merged